services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-revised-db-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tcss_460_backend
      MYSQL_USER: tyler_tcss460
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d 
volumes:
  db_data:
